### ISSUE TITLE
Data anomalies in 2014 Q4 published db

### ISSUE THREAD

**Issue by rebelslant** [vz-risk/veris#100]
Hey folks,
Just noticed that for the following incident ids, the timeline.incident.year appears as either 2102 or 2103. 

Cheers,
Bar

**Comment by gdbassett** [comment]
Go check years.

**Comment by gdbassett** [comment]
Checked and timeline.incident.year has been corrected in all VCDB records.  Also corrected two plus.dbir_year issues.  This has not been pushed to the CSV, joined json, or dataframe but is in the separated json.  Fixed in commit 7b2b1959c.
