### ISSUE TITLE
Reword "recently resigned" to "preparing to resign"

### ISSUE THREAD

**Issue by blackfist** [vz-risk/veris#107]
Right now under job changes we've got "recently resigned" which may or may not cover the case of an employee who is doing something while getting ready to resign. I suggest changing the label but not the actual enumeration to something like "preparing to resign or recently resigned"

**Comment by gdbassett** [comment]
changed description from "recently resigned" to "preparing to resign or recently resigned" in [dev e3e4ff7]

**Comment by gdbassett** [comment]
Discussion included separating them, but that would move 'recently resigned' to external which cause more issues with updating old records so agreed on just changing the description.

**Comment by gdbassett** [comment]
fixed in v1.3.1 dev [v1_3_1 6f9a362]
