### ISSUE TITLE
Rename integrity.variety.misappropriation to Repurpose

### ISSUE THREAD

**Issue by blackfist** [vz-risk/veris#12]
We use Misappropriation to indicate that an attacker made use of an asset for something that it wasn't intended for. For example, installing malware on a machine to participate in a Distributed Denial of Service attack. However, to many people the word misappropriation means that money was stolen. To make the intended purpose more clear, we are going to rename Misappropriation to Repurpose to indicate than an asset has been repurposed by an attacker.

**Comment by gdbassett** [comment]
done.
