### ISSUE TITLE
How should devices falling under 'IOT' be recorded?

### ISSUE THREAD

**Issue by gdbassett** [vz-risk/veris#122]
How should devices falling under 'IOT' be recorded?

Options include coding them as "SCADA" (becoming 'ICS').

Maybe a separate code? (It would be a group code that might have to be subsetted later)

**Comment by gdbassett** [comment]
We agreed to create new enumerations for IoT.  We also discussed creating a new superset.  There was some desire for 'IoT', however it is a use, not a device type.  The other option is something like 'embedded'.

**Comment by gdbassett** [comment]
My opinion would be to add a superset of `embedded` with varieties of `telemetry` and `telematics`
`asset.assets.e - telemetry` - `A dedicated device which collects data about the physical world`
`asset.assets.e - telematics` - `A dedicated device which affects the real world`

**Comment by Spitler** [comment]
After trying to improve on the above, I like what Gabe presented more and more. We don't want to enumerate specific objects/things or groups (wearables, home automation, etc.). The definitions of the above almost read like they are devices interacting with 'things' (collecting data from sensors or controlling them) as opposed to the objects or things themselves. I *think* we want to use DCS for the servers in the IoT environment, so we may want to add a bit of text that clears that up

**Comment by gdbassett** [comment]
Added in [v1_3_1 3e138cc].
