### ISSUE TITLE
Misrepresentation not well defined

### ISSUE THREAD

**Issue by gdbassett** [vz-risk/veris#244]
The 'misrepresentation' enumeration in 'integrity' is not well defined.

**Comment by jackson79** [comment]
> 
> 
> The 'misrepresentation' enumeration in 'integrity' is not well defined.

**Comment by scottmerck7007** [comment]
dismiss

**Comment by gdbassett** [comment]
"Misrepresentation" -> "compromise of authenticity (e.g. masquerading as the legitimate owner of an account)"
