### ISSUE TITLE
Should there be credential stuffing in action.malware

### ISSUE THREAD

**Issue by gdbassett** [vz-risk/veris#294]
Should there be credential stuffing in action.malware.  The reasoning being that credential stuffing is an automated attack, but 'use of stolen credentials' only occurs in 'action.hacking.

**Comment by nuryusy** [comment]
Evet

**Comment by nuryusy** [comment]
Ne yapmalıyım peki

**Comment by gdbassett** [comment]
automation from a attacker machine can still be considered hacking.  Malware would be from the victim's machine.  As such, no change needed.
