### ISSUE TITLE
Define 4A parents

### ISSUE THREAD

**Issue by gdbassett** [vz-risk/veris#298]
Add the 4A mid-level enumeration definitions as descriptions in the schema

Action: 
Hacking: Things more a person does at a keyboard (than by a program)
Malware: Things more done by a program (than a person on a keyboard)
Social, misuse, physical, error, environmental

Actor: internal, external, partner

Assets: server, person, user device, terminal, embedded, network, media

Attributes: Confidentiality, integrity, availability

**Comment by BryceGerhardt00** [comment]
[](url)

**Comment by gdbassett** [comment]
Suzanne will provide
