### ISSUE TITLE
action.social.target and asset.assets.P - have diverged

### ISSUE THREAD

**Issue by gdbassett** [vz-risk/veris#306]
through 1.3.3 action.social.target and asset.assets.P had the same enumerations.  This allowed filling in asset.assets.P from action.social.target and visa versa.  Now, "End-user or employee" is in action.social.target as a parent of "End-user" and "Other employee" while only "End-user" is included in asset.assets.P.  Since this was intentional per https://github.com/vz-risk/veris/issues/150, we probably need to consider how they should be mapped to each other in rules.py.

**Comment by Erin-max** [comment]
I have a problem understanding.  simple terms please
