### ISSUE TITLE
action.hacking.variety enumeration imports

### ISSUE THREAD

**Issue by krmaxwell** [vz-risk/veris#34]
From [veriscommunity.net](http://www.veriscommunity.net/doku.php?id=actions#variety1):

> VERIS uses WASC's Threat Classification as a baseline for this list; descriptions of these attacks [can be found there](http://projects.webappsec.org/w/page/13246978/Threat%20Classification). We have considered incorporating or allowing other attack classifications (e.g., [CAPEC](http://capec.mitre.org/)), and would appreciate feedback from the community on this.

I agree that we should consider importing the CAPEC dictionary for use here. It allows for better alignment with the STIX/TAXII stack and is far more comprehensive, at the cost of a much larger set here (perhaps we could avoid some child nodes below a certain depth).

Alternately, it might be worth mapping our (and WASC's) enumerations to that standard.

**Comment by gdbassett** [comment]
Overcome by events.  We have a history of enumerations, mainly based on ones we've found we needed to code.  We want to try and align veris enumerations to other schemas wherever possible, but what we have currently works.
