### ISSUE TITLE
Gov level differentiation field

### ISSUE THREAD

**Issue by swidup** [vz-risk/veris#347]
We get questions about whether we can give differentiation of risk on State/Local vs Federal government entities.  The Naics does not care, being more concerned about the .gov function than the level of gov it is.  I propose adding a field to the plus section that can have a value of SL (state/local) or Fed for those cases where we know the value.  We could then potentially provide data going forward.

**Comment by gdbassett** [comment]
Add as separate victim field
Make it mandatory
Add a rules.py to automatically fill it in if industry isn't 92.
