### ISSUE TITLE
Expand definition of Disable Controls to include more than just disabling

### ISSUE THREAD

**Issue by planglois925** [vz-risk/veris#385]
A lot of malware leverages different techniques than solely disabling controls, such as various evasion techniques that are enumerated as part of the MITRE ATT&CK framework. As it currently stands, the rigid definition of disable controls does not include these evasion methods and such can't be well mapped to any of the current enumerations.  So either a new enumeration should be added or Disable Controls should be expanded.

**Comment by gdbassett** [comment]
phil: separate 'evasion' action? Wrap in to 'disable controls'?

gabe: this is a property of the action (modifying the action so as to note get caught), not the action itself.  As such it doesn't belong in the event_chain (or attack flow).

Agreement to add 'Evasion' as variety for Hacking, Malware, Misuse.

**Comment by gdbassett** [comment]
definition: "modification of the action (rather than the system) to avoid detection."
