### ISSUE TITLE
Consider adding "routine internal maintenance" to discovery methods

### ISSUE THREAD

**Issue by whbaker** [vz-risk/veris#71]
Example is a skimmer discovered by routine checkup of ATM. Applies to systems/apps as well.

**Comment by gdbassett** [comment]
May be replacing something vague with something else vague. If we define them better, we might find we could use it.  For now though, we don't know we'd have enough records so we'll defer it.

**Comment by gdbassett** [comment]
Change "IT review" definition to be "Any routine maintenance, testing or review of it assets. (Includes inspect of assets, vulnerability scans, etc.)" rather than adding a new enumeration.

**Comment by gdbassett** [comment]
Updated in [v1_3_2 3f4076c]
