### ISSUE TITLE
Bring back discovery_method of Ext - unrelated party

### ISSUE THREAD

**Issue by blackfist** [vz-risk/veris#75]
I have seen a couple incidents where this might still be the best choice for discovery method.

For example, there was an incident where an insider was taking photographs of credit cards for ID theft purposes. The incident was reported to the victim company by the manager at the photo development place to which she took the photos for printing.

Another incident involved documents that were published to the website that had sensitive information in them. A concerned member of the community reported the publishing error to the victim organization.

**Comment by gdbassett** [comment]
added Ext - Other in [dev e3e4ff7]

**Comment by gdbassett** [comment]
Add external-other to 1.3.1

**Comment by gdbassett** [comment]
Added 'other' to 'discovery_method' for internal and external.  Also made the partner other/unknown descriptions and case consistent. [v1_3_1 a99325a]

**Comment by gdbassett** [comment]
Added to conversion script in commit [v1_3_1 1ed0187]
