### ISSUE TITLE
Add asset variety for configuration management

### ISSUE THREAD

**Issue by blackfist** [vz-risk/veris#76]
We already have a malware vector for software update where a compromised server that is trusted by a workstation sends malware. However, we might also need an asset variety to cover the compromised server. I would like to propose adding "S - Configuration management" to the asset enumeration to cover incidents like this one: http://classic.slashdot.org/story/14/05/17/051214

**Comment by gdbassett** [comment]
While we have seen incidents that could be coded this way, but we ultimately haven't seen it enough to make it worth adding yet.  When we start seeing it pop up enough in incidents, we'll add it.

**Comment by gdbassett** [comment]
In light of https://arstechnica.com/information-technology/2017/07/heavily-armed-police-raid-company-that-seeded-last-weeks-notpetya-outbreak/, https://www.cyberscoop.com/shadowpad-backdoor-netsarang-kaspersky-hong-kong/, and https://threatpost.com/seven-more-chrome-extensions-compromised/127458/, we may want to consider this.

**Comment by swidup** [comment]
https://www.bleepingcomputer.com/news/security/ukraine-fears-second-ransomware-outbreak-as-another-accounting-firm-got-hacked/

**Comment by gdbassett** [comment]
Asset.assets.S - Configuration or Patch Management: "Servers maintaining or deploying configurations or patches to other assets."

**Comment by gdbassett** [comment]
Updated in [v1_3_2 3f4076c]

**Comment by gdbassett** [comment]
added to partner survey template 1.3.2
