### ISSUE TITLE
checkvalidity script isn't checking data_victim

### ISSUE THREAD

**Issue by blackfist** [vz-risk/veris#77]
That's a new field. Need to put that in the build schema function in checkValidity1.3

**Comment by gdbassett** [comment]
Need to rewrite checkvalidity in python.

**Comment by blackfist** [comment]
Be prepared to grow a long white beard waiting for it to finish crunching
all your records.

**Comment by gdbassett** [comment]
`import multiprocessing` and 24 threads will just have to get me by.

**Comment by gdbassett** [comment]
Bhaskar may have done this in https://github.com/vz-risk/veris/blob/master/verify_keys.py.  Will test some time.

**Comment by gdbassett** [comment]
checkValidity rewritten in python and performance issues debugged.
