### ISSUE TITLE
Add field for total number of assets/systems compromised

### ISSUE THREAD

**Issue by whbaker** [vz-risk/veris#91]
We have the ability to add an amount for each variety of asset selected, but we do not have a single field that acts as a sum or total. The change would be similar to what we do with total number of records and then the ability to specific number for each variety.

**Comment by gdbassett** [comment]
There is a plus.asset.total, but it is a character vector of 'No' and 'Yes'.  Going to add asset.total_amount

**Comment by gdbassett** [comment]
added in v1.3.1 dev [v1_3_1 baf71b1]
