### ISSUE TITLE
Add physical.variety for "snap a picture"

### ISSUE THREAD

**Issue by whbaker** [vz-risk/veris#93]
We have "surveillance" but that seems extreme for a situation where, for instance, someone snaps a pic of info and then posts it on the internet.

**Comment by gdbassett** [comment]
We see the general intent, but feel that most cases where this would happen (e.g. medical worker taking a picture of a patient) would be misuse of existing privileges.

**Comment by gdbassett** [comment]
method of exfiltration rather than asset or action.

**Comment by gdbassett** [comment]
`action.physical.variety.Snap a picture`

**Comment by gdbassett** [comment]
<In next review consider adding `action.physical.variety.Snap picture`
