### ISSUE TITLE
Add "attribution method" to external actor

### ISSUE THREAD

**Issue by whbaker** [vz-risk/veris#95]
We used to have a field asking how attribution was determined (eg, arrest vs IP address). /we decided to take a more conservative approach and just do attribution when it's higher confidence, rendering this question unnecessary. However, I think we're missing out on potentially useful info. For instance, I just did a case where malware code, icon, etc was Russian. That's not high confidence, but is it better to assign origin as "Unknown" or provide "RU" and "determined via malware artifacts"? If we wanted to examine high confidence attribution only, then we can simply set a threshold using this field.

**Comment by gdbassett** [comment]
The suggestion makes sense, but we've never had a need for it to this point so no point changing it.

**Comment by gdbassett** [comment]
I think this ultimately should be 'don't fix'.  This kind of data can be captured in the notes.  It would be hard to implement and unlikely to collect enough data to utilize statistically.

**Comment by gdbassett** [comment]
Closing as in 2019 we again agree with the above assessment.
